# $Id$
# Makefile for the /contrib subdirectory


# by default do nothing
default:


# specific targets
install:
	cd src ; $(MAKE) ; $(MAKE) install

clean:
	cd src ; $(MAKE) clean
	-rm -r bin doc man share


